server:
  port: 8181
  servlet:
    context-path: /store-dev

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:D:\java-learn\geekbrains\spring-lesson-6\db\demo;MV_STORE=false
    username: sa
    password:

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl:
          auto: create

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false

  thymeleaf:
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
